CREATE TABLE IF NOT EXISTS `mask_info` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `MaskId` INT(11) NOT NULL,
  `ColorId` INT(11) NOT NULL COMMENT '口罩顏色',
  `QtyPerPack` INT(11) NOT NULL COMMENT '一盒數量',
  `CreateUser` VARCHAR(50) NOT NULL DEFAULT '',
  `CreateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdateUser` VARCHAR(50) NOT NULL DEFAULT '',
  `UpdateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '口罩款式基本資料';