CREATE TABLE IF NOT EXISTS `pharmacy_info` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `PharmacyId` INT(11) NOT NULL,
  `DayOfWeek` INT(11) NOT NULL COMMENT '星期幾',
  `OpenTime` TIME NOT NULL COMMENT '開門時間',
  `CloseTime` TIME NOT NULL COMMENT '關門時間',
  `CreateUser` VARCHAR(50) NOT NULL DEFAULT '',
  `CreateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdateUser` VARCHAR(50) NOT NULL DEFAULT '',
  `UpdateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '藥局營業基本資料';