CREATE TABLE IF NOT EXISTS `pharmacy_product` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `PharmacyId` INT(11) NOT NULL,
  `ProductTypeId` INT(11) NOT NULL COMMENT '藥局商品',
  `ProductDetailId` INT(10) NOT NULL,
  `Price` DECIMAL(20,4) NOT NULL DEFAULT '0.0000',
  `CreateUser` VARCHAR(50) NOT NULL DEFAULT '',
  `CreateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdateUser` VARCHAR(50) NOT NULL DEFAULT '',
  `UpdateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = '藥局商品資料';