CREATE TABLE `user_wallet_log` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`UserId` INT(10) NOT NULL,
	`Amount` DECIMAL(20,4) NOT NULL,
	`PreBalance` DECIMAL(20,4) NOT NULL,
	`LastBalance` DECIMAL(20,4) NOT NULL,
	`CreateUser` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`CreateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`UpdateUser` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`UpdateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`) USING BTREE
)
COMMENT='客戶錢包異動紀錄'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;