CREATE TABLE `user_wallet` (
	`Id` INT(10) NOT NULL AUTO_INCREMENT,
	`UserId` INT(10) NOT NULL,
	`CashBalance` DECIMAL(20,4) NOT NULL,
	`CreateUser` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`CreateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`UpdateUser` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8mb4_unicode_ci',
	`UpdateTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`) USING BTREE
)
COMMENT='客戶錢包資料'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;